[package]
authors = ["tony"]
description = "TONy Markdown App"
edition = "2021"
name = "tmd"
version = "0.2.1"

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]
name = "tmd_lib"

[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
base64 = "0.23.1"
dirs = "6.0.0"
notify = "8.2.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = ["macos-private-api"] }
tokio = { version = "1", features = ["time"] }
tauri-plugin-deep-link = "2"
tauri-plugin-dialog = "2"
tauri-plugin-global-shortcut = "2"
tauri-plugin-opener = "2"
tauri-plugin-single-instance = "2"
tauri-plugin-updater = "2"
trash = "5"
url = "2"
